version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:80"
    container_name: "codeplay"
    volumes:
      - .:/home/user/app
      
  db:
    image: mysql
    container_name: "codeplay_db"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: necronomicon
    ports:
      - "8001:3306"
    entrypoint: tail -f /dev/null

  # redis:
  #   image: redis
  #   container_name: "codeplay_redis_server"
  #   ports:
  #     - "8003:6379"

  # kafka:
  #   image: bitnami/kafka
  #   container_name: "codeplay_kafka_service"
  #   ports:
  #     - "8002:2181"
